# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Test\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Test\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    Test\Domain\Team\TeamRepositoryInterface: '@Test\Infrastructure\Doctrine\TeamRepository'
    Test\Domain\Game\GameRepositoryInterface: '@Test\Infrastructure\Doctrine\GameRepository'
    Test\Domain\Player\PlayerRepositoryInterface: '@Test\Infrastructure\Doctrine\PlayerRepository'
    Test\Domain\League\LeagueRepositoryInterface: '@Test\Infrastructure\Doctrine\LeagueRepository'
    Test\Infrastructure\Services\FetchGamesInterface: '@Test\Infrastructure\Services\FetchGames'
    Test\Infrastructure\Services\FetchLeaguesInterface: '@Test\Infrastructure\Services\FetchLeagues'
    Test\Infrastructure\Services\FetchTeamsInterface: '@Test\Infrastructure\Services\FetchTeams'

    Test\Infrastructure\Storage\UploadFile:
        arguments:
            $targetDirectory: 'images'